### obtener todos los categorias
GET http://localhost:3000/api/categoria

### obtener un categoria
GET http://localhost:3000/api/categoria/1

### crear un nuevo categoria
POST http://localhost:3000/api/categoria
Content-Type: application/json

{
"name": "Lacteos",
"description": "leche, queso, manteca"
}

### modificar un categoria (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/categoria/7
Content-Type: application/json

{
"name": "Cariniceria",
"descripcion": "carnes y fiambres"
} 

### modificar un categoria (PATCH - recurso parcial)
PATCH http://localhost:3000/api/categoria/7
Content-Type: application/json

{
  "descripcion": "carnes y achuras"
}

### borrar un categoria
DELETE http://localhost:3000/api/categoria/7