### obtener todos los clientes
GET http://localhost:3000/api/cliente


### obtener un cliente
GET http://localhost:3000/api/cliente/a02b91bc-3769-4221-beb1-d7a3aeba7dad


### crear un nuevo cliente
POST http://localhost:3000/api/cliente
Content-Type: application/json

{
  "name": "Ignacio",
  "apellido": "Corsalini",
  "dni": "45504158",
  "usuario": "ignacioCorsalini@gmail.com",
  "contraseña":"$2b$10$6DBsy2STGClEOGFYr1S8dubdPRdpdMpiRmuQM12y9yrtZLcrjKINO",
  "zona": 2
}
### Si el rol es true, es admin, si es false es cliente

### modificar un cliente (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/cliente/1
Content-Type: application/json

{
  "name": "Luciana",
  "apellido": "Echeveste",
  "dni": "87654321",
  "usuario": "lucianaEcheveste",
  "contraseña":"54321",
  "rol": false, // false = cliente, true = admin
  "zona": 2
} 

### modificar un cliente (PATCH - recurso parcial)
PATCH http://localhost:3000/api/cliente/2
Content-Type: application/json

{ 
  "rol": true
}

###"contraseña": "$2b$10$6DBsy2STGClEOGFYr1S8dubdPRdpdMpiRmuQM12y9yrtZLcrjKINO"

### borrar un cliente
DELETE http://localhost:3000/api/cliente/1