### obtener todos los clientes
GET http://localhost:3000/api/cliente


### obtener un cliente
GET http://localhost:3000/api/cliente/a02b91bc-3769-4221-beb1-d7a3aeba7dad


### crear un nuevo cliente
POST http://localhost:3000/api/cliente
Content-Type: application/json

{
  "name": "Ignacio",
  "apeellido": "Corsallini",
  "usuario": "ignacioCorsallini",
  "contraseña":"12345",
  "zona": "zona2"
}

### modificar un cliente (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/cliente/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
  "name": "Luciana",
  "apellido": "Echeveste",
  "usuario": "lucianaEcheveste",
  "contraseña":"54321",
  "zona": "zona3"
} 

### modificar un cliente (PATCH - recurso parcial)
PATCH http://localhost:3000/api/cliente/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
  "contraseña":"123",
  "zona": "zona4"
}

### borrar un cliente
DELETE http://localhost:3000/api/cliente/a02b91bc-3769-4221-beb1-d7a3aeba7dad