### obtener todos los distribuidores
GET http://localhost:3000/api/distribuidor


### obtener un distribuidor
GET http://localhost:3000/api/distribuidor/1


### crear un nuevo distribuidor
POST http://localhost:3000/api/distribuidor
Content-Type: application/json

{
  "name": "Ignacio",
  "apellido": "Corsallini",
  "dni": "12345678",
  "valorEntrega":"12345",
  "zona": 2
}

### modificar un distribuidor (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/distribuidor/1
Content-Type: application/json

{
  "name": "Ignacio",
  "apellido": "Corsallini",
  "dni": "12345678",
  "valorEntrega":"120",
  "zona": 1
} 

### modificar un distribuidor (PATCH - recurso parcial)
PATCH http://localhost:3000/api/distribuidor/1
Content-Type: application/json

{
 "valorEntrega": "67890"
}

### borrar un distribuidor
DELETE http://localhost:3000/api/distribuidor/1