### obtener todos los Productos
GET http://localhost:3000/api/producto


### obtener un Productos
GET http://localhost:3000/api/producto/a02b91bc-3769-4221-beb1-d7a3aeba7dad


### crear un nuevo Productos
POST http://localhost:3000/api/producto
Content-Type: application/json

{
  "name": "Fideos",
  "descripcion": "Precio por unidad",
  "precio": 800,
  "stock": 15,
  "imagen":"../imagenes/pasta.png",
  "categoria": 5
}

### modificar un Productos (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/producto/2
Content-Type: application/json

{
  "name": "vacio",
  "descripcion": "carnes",
  "precio": 10000,
  "imagen":"...",
  "categoria": 2
} 

### modificar un Productos (PATCH - recurso parcial)
PATCH http://localhost:3000/api/producto/1
Content-Type: application/json

{
"imagen":"https://supermercado-backend-production.up.railway.app/public/imagenes/vacio.png"
}

### borrar un Productos
DELETE http://localhost:3000/api/producto/1