### obtener todos los Productos
GET http://localhost:3000/api/producto


### obtener un Productos
GET http://localhost:3000/api/producto/a02b91bc-3769-4221-beb1-d7a3aeba7dad


### crear un nuevo Productos
POST http://localhost:3000/api/producto
Content-Type: application/json

{
  "name": "leche entera",
  "descripcion": "lacteo",
  "precio": 500,
  "stock": 5,
  "imagen":"...",
  "categoria": 1
}

### modificar un Productos (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/producto/2
Content-Type: application/json

{
  "name": "vacio",
  "descripcion": "carnes",
  "precio": 10000,
  "imagen":"...",
  "categoria": 2
} 

### modificar un Productos (PATCH - recurso parcial)
PATCH http://localhost:3000/api/producto/83e10d7d-8f58-402a-9054-0de8e0f384fb
Content-Type: application/json

{
"precio": 150
}

### borrar un Productos
DELETE http://localhost:3000/api/producto/a02b91bc-3769-4221-beb1-d7a3aeba7dad