### obtener todos los Zonas
GET http://localhost:3000/api/zona

### obtener un zona
GET http://localhost:3000/api/zona/2

### crear un nuevo zona
POST http://localhost:3000/api/zona
Content-Type: application/json

{
  "name": "Zona Oeste",
  "description": "Entre oroño y el rio"
}

### modificar un zona (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/zona/5
Content-Type: application/json

{
  "name": "Zona Oeste",
  "description": "cambio descripcion y zona"
} 

### modificar un zona (PATCH - recurso parcial)
PATCH http://localhost:3000/api/zona/5
Content-Type: application/json

{
"description": "cambio descripcion solo"
}

### borrar un zona
DELETE http://localhost:3000/api/zona/4